#!/bin/bash
dir=`pwd`

cd ~

do_ln()
{
  if [ ! -h ~/$1 ]; then ln -s $dir/$1 ~/$1; fi
}

do_ln .bashrc
do_ln .zsrc
do_ln .vimrc
do_ln .tmux.conf
do_ln .gitconfig
do_ln .gitignore
do_ln .githelpers
do_ln .gdbinit

